[tool.black]
line_length = 88

[tool.isort]
profile = "black"
lines_after_imports = 2

[tool.pytest.ini_options]
django_find_project = true
python_files = [
    "**/*_test*.py",
    "**/tests.py",
    "**/tests_*.py",
]

[tool.mypy]
plugins = ["mypy_django_plugin.main"]

[tool.django-stubs]
django_settings_module = "config.settings"
